name: Deploy Demo

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup NodeJS
              uses: actions/setup-node@v4
              with:
                  node-version: 14

            - name: Install Dependencies
              run: npm ci

            - name: Build
              run: npm run build

            - name: SSH Deploy
              uses: easingthemes/ssh-deploy@v5.1.0
              with:
                  SSH_PRIVATE_KEY: ${{ secrets.PRIVATEKEY }}
                  ARGS: '-rlgoDzvc -i'
                  REMOTE_HOST: ${{ secrets.HOST }}
                  REMOTE_USER: ${{ secrets.USERNAME }}
                  SOURCE: 'build/*'
                  TARGET: ${{ secrets.TARGETPATH }}
                  EXCLUDE: '.git, /node_modules/'
                  SCRIPT_BEFORE_REQUIRED: true
                  SCRIPT_BEFORE: |
                      ls -al ${{ secrets.TARGETPATH }}
                      rm -r ${{ secrets.TARGETPATH }}/*
                  SCRIPT_AFTER: |
                      ls -al ${{ secrets.TARGETPATH }}
                      echo $RSYNC_STDOUT
