name: Deploy Demo

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup NodeJS
              uses: actions/setup-node@v4
              with:
                  node-version: 14

            - name: Install Dependencies
              run: npm ci

            - name: Build
              run: npm run build

            - name: SSH Tool
              uses: Comori/ssh@v0.0.7
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  privateKey: ${{ secrets.PRIVATEKEY }}
                  command: |
                      rm -r ${{ secrets.TARGETPATH }}/*
                  sourceFiles: |
                      build/*
                  targetDir: ${{ secrets.TARGETPATH }}
